name: InfiniteBot3
main: com.illtamer.infinite.bot.minecraft.Bootstrap
version: 3.1.6

author: IllTamer

load: POSTWORLD

softdepend:
  - PlaceholderAPI
  - PlayerPoints
  - Vault

commands:
  InfiniteBot3:
    aliases:
      - ib3